### ISSUE TITLE
Variable not needed

### ISSUE THREAD

**Issue by amitmerchant1990** [IonicaBizau/worder#5]
Hi,

While going through the code base, I found that in https://github.com/IonicaBizau/worder/blob/master/lib/index.js the `var pattern` is sort of useless. Why not to consider cleaning the same?

Thanks!

**Comment by IonicaBizau** [comment]
Ummm, good point. It looks like it comes from #1. Taking a look.

**Comment by IonicaBizau** [comment]
:ship: **`1.0.3`** :tada: Fixed via #6
